"""initial schema

Revision ID: 47a7b037d259
Revises: 
Create Date: 2026-03-24 13:47:07.736886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a7b037d259'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_dreams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dream_role', sa.String(), nullable=True),
    sa.Column('dream_industry', sa.String(), nullable=True),
    sa.Column('dream_location', sa.String(), nullable=True),
    sa.Column('timeline_months', sa.Integer(), nullable=True),
    sa.Column('gap_report', sa.JSON(), nullable=True),
    sa.Column('timeline_plan', sa.JSON(), nullable=True),
    sa.Column('feasibility_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_dreams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_dreams_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('application_records', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_application_records_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_records_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'job_listings', ['job_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ats_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('missing_keywords', sa.JSON(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('doc_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'job_listings', ['job_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('market_insights', schema=None) as batch_op:
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('industry',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_market_insights_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_insights_region'), ['region'], unique=False)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('name_enc',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('email_enc',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email_enc',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name_enc',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('market_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_insights_region'))
        batch_op.drop_index(batch_op.f('ix_market_insights_industry'))
        batch_op.alter_column('industry',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'job_listings', ['job_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_generated_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_generated_documents_job_id'))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('doc_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('missing_keywords')
        batch_op.drop_column('ats_score')

    with op.batch_alter_table('application_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'job_listings', ['job_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_application_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_application_records_status'))
        batch_op.drop_index(batch_op.f('ix_application_records_job_id'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('career_dreams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_dreams_user_id'))

    op.drop_table('career_dreams')
    # ### end Alembic commands ###
